### ISSUE TITLE
cargo and rustc no longer in `$PATH`

### ISSUE THREAD

**Issue by yonran** [jimmycuadra/docker-rust#14]
As of jimmycuadra/rust:1.19.0, cargo is no longer in `$PATH`:

    $ docker run -it --rm -v $(pwd):/source -v ~/.cargo-linux:/root/.cargo jimmycuadra/rust:1.19.0  cargo build
    docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"cargo\": executable file not found in $PATH".

I have to manually set `$PATH` in order to use it:

    docker run -it --rm -v $(pwd):/source -v ~/.cargo-linux:/root/.cargo jimmycuadra/rust:1.19.0 bash -c 'PATH=$PATH:/root/.rustup/toolchains/1.19.0-x86_64-unknown-linux-gnu/bin cargo build'

**Comment by jimmycuadra** [comment]
I think the problem is that you're overwriting the directory where the executable lives by doing this:

```
-v ~/.cargo-linux:/root/.cargo
```

The executables live in `/root/.cargo/bin`, [which is included in PATH](https://github.com/jimmycuadra/docker-rust/blob/f5c0ba6a9ff22d2e85670564eb05f00b2fc5c42a/Dockerfile#L27), but the above volume mount will overwrite the parent directory with your host directory.

**Comment by yonran** [comment]
You are correct. Thank you. I can switch to using the following `-v` command to mount the registry:

    docker run -it --rm -v $(pwd):/source -v ~/.cargo-linux/registry:/root/.cargo/registry jimmycuadra/rust:1.19.0 cargo build --release

**Comment by jimmycuadra** [comment]
If you ever end up using Git dependencies, you'll probably want to create a volume for `/root/.cargo/git` too. It lives alongside `registry` but is used for cloning Git repos.
