### ISSUE TITLE
cargo won't build - can't fetch from github.com

### ISSUE THREAD

**Issue by MihaMarkic** [jimmycuadra/docker-rust#9]
Getting this

> Updating registry `https://github.com/rust-lang/crates.io-index`
> warning: spurious network error (2 tries remaining): [12/-1] Unexpected HTTP status code: 504
> warning: spurious network error (1 tries remaining): [12/-1] Unexpected HTTP status code: 504

Not sure why as ping to github works.

**Comment by jimmycuadra** [comment]
Looks like a networking issue. There are lots of reasons why GitHub might be having problems and returning HTTP 504s even if you can ping them. The ping just means you're able to send an ICMP packet to them and get a response. In any case, this isn't a problem with this Docker image itself, so I am going to close this. You might want to just try again later in case the problem was a temporary network issue.

**Comment by MihaMarkic** [comment]
I know what ping is :-). If I use Ubuntu image and install rust manually it just works. Hence it is something related to this or underlying image. I guess.
